#!/bin/sh
export ROOT="/mnt/SDCARD"
export LD_LIBRARY_PATH="$ROOT/.tmp_update/lib:/lib:/config/lib:/customer/lib"
export PATH="$ROOT/.tmp_update/bin:$PATH"

# init backlight
echo 0 > /sys/class/pwm/pwmchip0/export
echo 800 > /sys/class/pwm/pwmchip0/pwm0/period
echo 6 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable

# init lcd
cat /proc/ls
sleep 0.25

if [ -f /customer/app/axp_test ]; then
	export MODEL=354

	# kill default telnetd. Allium will launch its own if needed
	killall telnetd
else
	export MODEL=283

	# init charger detection
	if [ ! -f /sys/devices/gpiochip0/gpio/gpio59/direction ]; then
		echo 59 > /sys/class/gpio/export
		echo in > /sys/devices/gpiochip0/gpio/gpio59/direction
	fi

	# add a loopback address for RA network interface
	ip addr add 127.0.0.1/8 dev lo
	ifconfig lo up
fi

# use audioserver to prevent pop-noise
if [ -f /customer/lib/libpadsp.so ]; then
	LD_PRELOAD=as_preload.so audioserver_"$MODEL" &
	export LD_PRELOAD=libpadsp.so
fi

# run Allium
RUST_LOG=debug RUST_BACKTRACE=1 /mnt/SDCARD/.allium/bin/alliumd > /mnt/SDCARD/.allium/alliumd.log 2>&1

while true; do
	reboot
	sleep 10
done
