[package]
name = "common"
version = "0.26.0"
edition = "2021"

[lib]
name = "common"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
simulator = ["minifb"]
miyoo = ["evdev", "framebuffer", "sysfs_gpio"]

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
chrono = { version = "0.4.29", features = ["serde"] }
enum-map = "2.5.0"
fluent-templates = { git = "https://github.com/goweiwen/fluent-templates", branch = "ignore", version = "0.8.0", features = ["walkdir"], default-features = false }
image = { version = "0.23", default-features = false, features = ["gif", "jpeg", "png"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
log = { version = "0.4.19", features = ["release_max_level_info"] }
nix = "0.23"
rusqlite = { version = "0.31", features = ["bundled", "chrono"] }
rusqlite_migration = "1.0.2"
rusttype = "0.9.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
type-map = "0.4.0"
sysfs_gpio = { version = "0.6.1", optional = true }
wait-timeout = "0.2.0"
fast_image_resize = "2.7.3"
bytemuck = "1.16.0"
minifb = { version = "0.27", optional = true }
evdev = { version = "0.12.1", features = ["tokio"], optional = true }
framebuffer = { version = "0.3.1", optional = true }
crossbeam = "0.8.4"
iced = { git = "https://github.com/iced-rs/iced.git" }
iced_graphics = { git = "https://github.com/iced-rs/iced.git" }
iced_tiny_skia = { git = "https://github.com/iced-rs/iced.git" }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git" }
iced_runtime = { git = "https://github.com/iced-rs/iced.git" }
iced_renderer = { git = "https://github.com/iced-rs/iced.git" }
iced_core = { git = "https://github.com/iced-rs/iced.git" }
