export SHELL=/mnt/SDCARD/App/BetterWifi/
export PROMPT='%n@%m %~ %# '
export sysdir=/mnt/SDCARD/.tmp_update
export miyoodir=/mnt/SDCARD/miyoo
export LD_LIBRARY_PATH="/mnt/SDCARD/App/BetterWifi/lib:/lib:/config/lib:$miyoodir/lib:$sysdir/lib:$sysdir/lib/parasyte"
export PATH="$sysdir/bin:$PATH:$SHELL/"
export ZDOTDIR="/mnt/SDCARD/App/BetterWifi/share/zsh/5.9/functions"
export ZSH_CACHE_DIR="/mnt/SDCARD/App/BetterWifi/share/zsh"
export TERMINFO="/mnt/SDCARD/App/BetterWifi/share/terminfo"
export TERM="vt102"