name: Release

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  create-release:
    name: deploy
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ armv7-unknown-linux-gnueabihf ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Setup build toolchain
        uses: ./.github/actions/setup-build

      - name: Build target
        run: cargo zigbuild --release --bins --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          make all
          cd dist
          zip -r ../allium-${{ matrix.target }}.zip .allium .tmp_update RetroArch Apps BIOS Roms Saves Themes
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: 'allium-${{ matrix.target }}.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
